### ISSUE TITLE
Problem with queries

### ISSUE THREAD

**Issue by Hemualliug** [ld4mbse/oslc4tdb#4]
Hello, 

I'm currently using OSLC4TDB for a school project. Everything is working but I don't understand how to build a specific query.
At first, I created a store named myStore, then created a Graph named myGraph with the following SHACL Schema : 

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix oslc: <http://open-services.net/ns/core#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix dcterms: <http://purl.org/dc/terms/> .

<urn:PersonShape> a sh:NodeShape ;
 sh:targetClass foaf:Person ;
 rdfs:label "Person" ;
 sh:property [
     sh:path foaf:name ;
     sh:nodeKind sh:Literal ;
     sh:datatype xsd:string ;
 ] ;
.

<urn:DogShape> a sh:NodeShape ;
 sh:targetClass foaf:Dog ;
 rdfs:label "Dog" ;
 sh:property [
     sh:path foaf:familyName ;
     sh:nodeKind sh:Literal ;
     sh:datatype xsd:string ;
 ] ;
.

I inserted some data in my graph: 

<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:foaf="http://xmlns.com/foaf/0.1/">
	<rdf:Description rdf:about="Dog/1">
		<foaf:familyName>Fido</foaf:familyName>
		<rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Dog" />
	</rdf:Description>
	<rdf:Description rdf:about="Dog/2">
		<foaf:familyName>Doggy</foaf:familyName>
		<rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Dog" />
	</rdf:Description>
</rdf:RDF>

Finally, I would like to ask my graph to return me the resource which contains the dog "Doggy" so I tried these 2 requests but no one worked : 
GET http://localhost:8080/oslc4tdb/oslc/myStore/myGraph/Dog?oslc.select=foaf:familyName="Doggy"
GET http://localhost:8080/oslc4tdb/oslc/myStore/myGraph/Dog?oslc.where=foaf:familyName="Doggy"

I'm sending my request via Insomnia REST Client.
The error is "Bad formed properties".

Thank you for you time and help.

Guillaume H.

**Comment by isccarrasco** [comment]
Hello @Hemualliug.

I was reviewing the issue you mentioned, and it seems to me that you are missing to add the `oslc.prefix` parameter to teach the query how to interpret the `foaf` namespace.

By doing something like:

```
GET http://localhost:8080/oslc4tdb/oslc/mystore/mygraph/Dog\
?oslc.prefix=foaf=<http://xmlns.com/foaf/0.1/>\
&oslc.select=foaf:familyName
```

Will return:

```rdf
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:oslc="http://open-services.net/ns/core#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
    <oslc:ResponseInfo rdf:about="http://localhost:8080/oslc4tdb/oslc/mystore/mygraph/Dog">
        <oslc:totalCount rdf:datatype="http://www.w3.org/2001/XMLSchema#integer"
    >2</oslc:totalCount>
        <rdfs:member>
            <rdf:Description rdf:about="http://localhost:8080/oslc4tdb/oslc/mystore/mygraph/Dog/2">
                <foaf:familyName>Doggy</foaf:familyName>
            </rdf:Description>
        </rdfs:member>
        <rdfs:member>
            <rdf:Description rdf:about="http://localhost:8080/oslc4tdb/oslc/mystore/mygraph/Dog/1">
                <foaf:familyName>Fido by bulk loader</foaf:familyName>
            </rdf:Description>
        </rdfs:member>
    </oslc:ResponseInfo>
</rdf:RDF>
```

In the other hand you can use `oslc.select` to specify the property you want to retrieve.

You can see the specification in the next link

[https://archive.open-services.net/bin/view/Main/OSLCCoreSpecQuery](https://archive.open-services.net/bin/view/Main/OSLCCoreSpecQuery)

Regards!

**Comment by Hemualliug** [comment]
Hello,

I have lots of work and I realized that I didn't thank you for you time and
your complete answer that really helped me. Thank you.

Regards,

Guillaume Hutin
